FROM ruby:3.3

# Set working directory
WORKDIR /app

# Install dependencies
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client

# Install bundler and set up cache
COPY Gemfile Gemfile.lock ./
RUN gem install bundler && bundle install

# Copy the rest of the app
COPY . .

EXPOSE 3000
